language: java
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: fyzvhspR3Uvx/2jk1HXTPfttbaFE81LISfWbA5/zL/cglKpMYPCXU+ikLrDgkUp5IrUpvVeor4W255lhH0fKa2+WZcJ967ccCCYAEJN13hQWXhonB4bQUKW2OuaH02CazBJWGiOit80oueXZmSLA3B0aO9AnkYd21Hwz8oB6nalyeUQQIA6dKAB1yDzztkXSK4G3zENku31uFNuP2dV4aJEbHYoNCScUtX/8UnE+63Oe5t48wLeyOcY5uo66ebXH3IVU9vUp7UqGtbr/URCH3y/rmdRDRMhEBJwUDBKi3D8Lg7hQ18/AlCR1DTaUYeH5ilMUPxMMVAAR/TCBU30gOUQVz0rl9NTSdbTvlQB+wbQSEqy/dQvA57QJ/lOg+t9HPZdNKd2zcHddQExGhyJyIRoctMBpbL45ElWUQhDfg6yoZzhDrBIXlEcv2UOGqLEHGkfExYN5sxSXpmHWMPV8KDhypi/c3v/Qm4EWs/8O6PCrixxbTnQgBq97xSwM/7XIW3PGOvQ6q3gJGcPy7aJ+bBeQtXHwSnheyoS8kh842q6ZNuJ7bA0G6t3Tp2QduRKGmpZSQ7KzE2awAlJTp1gbvs7PR8QVcYvGP6oH5brbhsAQTqrFZJwB7FqHVuhBJlDgVcS9/c302eSk/veAdBFaxDTCd0PguTybbcptSAk84+w=
  app:
      heroku: material-contacts-apispark
